### ISSUE TITLE
[DOCS-390] Missing page

### ISSUE THREAD

**Issue by Hiooo** [codacy/docs#1285]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [x ] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

**Affected pages**
This feedback applies to the following documentation pages / URLs:

http://docs.codacy.com/docs/security

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

"
Oops!
Couldn't find the page you're looking for
"

**Comment by prcr** [comment]
Hello @Hiooo, and thank you for reporting this.

For more context, could you tell us the site or page that includes a link to the missing page? Since the missing page that you reported never existed, we'd like to fix the broken link if possible.

**Comment by prcr** [comment]
In the meanwhile, I created a redirect from https://docs.codacy.com/docs/security to https://security.codacy.com/.

Depending on the context where the broken link may appear, the new target page may or may not be the most appropriate one.

**Comment by prcr** [comment]
I'm closing this issue now, but do let us know if you can provide more info. Thank you!

**Comment by Hiooo** [comment]
Hi, sorry for late reply.

I found the link under Third-party application access policy,  Codacy Login, app, 
<img width="902" alt="Skjermbilde 2022-07-06 kl  12 24 51" src="https://user-images.githubusercontent.com/15194429/177529692-5b096715-7343-4987-833a-b06041adbd3c.png">
description :)

**Comment by prcr** [comment]
Thanks for the extra details @Hiooo! I was now able to update the description with the correct URL:

![image](https://user-images.githubusercontent.com/60105800/177734882-1afde96f-6764-4e4e-a67d-34051011554e.png)
