### ISSUE TITLE
[DOCS-397] Why can't I see or add my organization's repositories? Information outdated

### ISSUE THREAD

**Issue by joanaviolante** [codacy/docs#1295]
There are several differences we notice at the moment, as this page is outdated. 

I am using Madalena's quote and screenshots to explain the differences: 
"
- In my personal GH account I see the Codacy App under Installed GitHub Apps rather than Authorized OAuth Apps;
- I don’t see the option “Revoke”, instead I see “Uninstall”;
- In my org, the App is under GitHub Apps on the side menu (and again I see “Uninstall”, not “Revoke”);
- When I uninstall the App from my org on GH and then go to re-install it, I see Install & Authorize (instead of Authorize qamine)
"

**Affected pages**
https://docs.codacy.com/faq/repositories/why-cant-i-see-or-add-my-organizations-repositories/ 
<img width="826" alt="Screenshot 2022-07-07 at 11 45 38" src="https://user-images.githubusercontent.com/106742866/177749365-53187193-b873-4c81-8e92-a00504487be7.png">
<img width="819" alt="Screenshot 2022-07-07 at 11 46 01" src="https://user-images.githubusercontent.com/106742866/177749374-fd2a4e5f-5fc5-44ea-969f-dbf0190191d8.png">
<img width="284" alt="Screenshot 2022-07-07 at 11 47 13" src="https://user-images.githubusercontent.com/106742866/177749375-f498e968-cbd8-413a-b201-ea001f741374.png">
<img width="534" alt="Screenshot 2022-07-07 at 11 50 08" src="https://user-images.githubusercontent.com/106742866/177749377-434375e1-36cd-4fcc-af9c-2867f3165230.png">

**Comment by prcr** [comment]
Besides updating the instructions for GitHub, we should also include instructions for GitLab and Bitbucket

**Comment by prcr** [comment]
The page mentioned in the feedback was actually removed in [DOCS-397](https://codacy.atlassian.net/browse/DOCS-397) since the information there no longer applies.
