### ISSUE TITLE
[DOCS-402] Improve visibility into issues category on docs page: "Which metrics does Codacy calculate?"

### ISSUE THREAD

**Issue by haiack** [codacy/docs#1316]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [x] Enhancement
-   [ ] Other

**Feedback**

The documentation page [Which metrics does Codacy calculate?] is great to give feedback on all the metrics Codacy can provide. However, when addressing the issues, which is one of the main features, it is unclear which types of issues Codacy identifies. 

I propose adding a link in the highlighted area of the screenshot to the page: "https://docs.codacy.com/repositories/issues/#filtering-issues".  Or something to that effect.

![image](https://user-images.githubusercontent.com/84727403/179730087-7740bd64-d86e-4e4e-8daf-e7ebdd022f4a.png)

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/faq/code-analysis/which-metrics-does-codacy-calculate/#issues 

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment]
It should be possible to reuse the [list of categories](https://docs.codacy.com/repositories/issues/#filtering-issues) directly on the page "Which metrics does Codacy calculate?".
