### ISSUE TITLE
[DOCS-403] Missing information on what data is removed when deleting an organization

### ISSUE THREAD

**Issue by caxaria** [codacy/docs#1321]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

From a user perspective, its very important to understand when or how does Codacy completely remove their data from the platform. In this case, how can they guarantee that their code is completely removed from Codacy. 

To this effect, I would add the information on the page that talks about removing user organizations:
- [ ] [Deleting an org](https://docs.codacy.com/organizations/what-are-synced-organizations/#deleting-an-organization) : Removes all configurations and source-code (repos) that belong to that organization from Codacy

**Affected pages**
This feedback applies to the following documentation pages / URLs:
https://docs.codacy.com/organizations/what-are-synced-organizations/#deleting-an-organization

**Additional context**
Other data removing pages: 

- [x]  [Deleting a repo](https://docs.codacy.com/repositories-configure/removing-your-repository/) : Already states that data related to that repo is removed from Codacy 
- [x] [Deleting an account](https://docs.codacy.com/account/managing-your-profile/#deleting-your-account) : Already states that data related (including repos) to that account is removed from Codacy 

So, it seems that deleting a org is the only part of our docs that is missing that repos and data get removed from Codacy.

**Comment by prcr** [comment]
For more context on this feedback, see [this internal Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1658420354938219).

**Comment by prcr** [comment]
The following pages are now updated:

- https://docs.codacy.org/organizations/what-are-synced-organizations/#deleting-an-organization
- https://docs.codacy.org/repositories-configure/removing-your-repository/
- https://docs.codacy.org/account/managing-your-profile/#deleting-your-account
