### ISSUE TITLE
[DOCS-406] Feedback on "Adding coverage to your repository"

### ISSUE THREAD

**Issue by mcreenan** [codacy/docs#1371]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

The documentation for adding coverage to your repository does not document the fact that you have to call the `final` command for Codacy to process the coverage reports.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/coverage-reporter/
https://docs.codacy.com/coverage-reporter/alternative-ways-of-running-coverage-reporter/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment]
Hi @mcreenan, and thank you for taking the time to submit your feedback!

The `final` command is indeed necessary if you're uploading multiple coverage reports, and the full sequence of commands is currently documented on this page dedicated to more advanced scenarios: [Uploading reports in sequence](https://docs.codacy.com/coverage-reporter/uploading-coverage-in-advanced-scenarios/#multiple-reports-sequence).

To help us better understand how to make this information more prominent on the documentation or even how to improve the feedback directly on the Codacy UI, could you please tell us some more details about the steps that you followed while setting up coverage, and what was the path that you followed while consulting the documentation?

**Comment by mcreenan** [comment]
Hi @prcr ,

Thanks for the response.

Looks like I misunderstood and was confused by a red herring in my testing.  

No issues here, so I'll close this out.
