### ISSUE TITLE
[DOCS-407] Add more details to "How long does it take for my repository to be analyzed?"

### ISSUE THREAD

**Issue by prcr** [codacy/docs#1372]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [x] Enhancement
-   [ ] Other

**Feedback**

We should help set the expectations regarding the time it takes Codacy to analyze a repository by providing more details about the factors that can affect the analysis times.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

A few example factors that affect the analysis times:

- If it's the first analysis of a repository
- Size of the repository
- Repositories in Open Source organizations have a lower priority to be analyzed
- Peak hours or issues affecting Codacy
- The time it takes the Git providers to call the webhooks on Codacy

**Comment by mrfyda** [comment]
💡 I think it might help to show on this page:
* if Codacy is currently experiencing an outage
* the current queue wait times

**Comment by prcr** [comment]
We improved the page [How long does it take for my repository to be analyzed?](https://docs.codacy.com/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed/) by including a list of reasons that can affect the analysis times, with workarounds for some of the items.



> I think it might help to show on this page:
> 
> * if Codacy is currently experiencing an outage
> * the current queue wait times

For now, we don't have a straightforward way to include dynamic information on our documentation pages. We do link to the Codacy status page. :+1: 

We'll continue to improve the page if there is more feedback or new insights.
