### ISSUE TITLE
[DOCS-431] Move info on how to change email address on Codacy to Your account > Emails

### ISSUE THREAD

**Issue by prcr** [codacy/docs#1425]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [X] Enhancement
-   [ ] Other

**Feedback**

The info on the page "How do I change my email address on Codacy?", now living under the FAQs, should be part of the [Emails](https://docs.codacy.com/account/emails/) page.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/faq/general/how-do-i-change-my-email-address-on-codacy/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

We should add a redirect from the page in the FAQ to the existing Emails page to avoid broken links.

**Comment by nicklem** [comment]
We updated the page with PR https://github.com/codacy/docs/pull/1543.
The update is now live at https://docs.codacy.com/account/emails/#updating-your-email-addresses
