### ISSUE TITLE
[DOCS-168] Missing documentation on possible issues 

### ISSUE THREAD

**Issue by IGFCoimbra** [codacy/docs#143]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**
We are missing documentation on possible issues. We should at least have a page explaining what they are, why they are flagged and the differences to the user

**Affected pages**
This feedback applies to the following documentation pages / URLs:
The New and Solved issues tabs on both PRs and commits

**Priority**
-   [ ] High
-   [X] Medium
-   [ ] Low

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment]
There's internal documentation describing the concept of possible issues:

https://docs.google.com/document/d/1RQA8LY06CcA-fjWHoCVWf5LKopUXBwR-66zXsOSTHtE/edit#heading=h.wxjuwwb224nr

**Comment by prcr** [comment]
@madalenamelo also provided the feedback below on 2021-08-06:

---

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories/issues/
https://docs.codacy.com/repositories/commits/#commits-page

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

The "possible new issues" and "possible fixed issues" are not mentioned in the documentation. These concepts are different from the New issues and Fixed issues and are not reported in the commits list but if you open the commit you can expand them and see a list of issues under the relevant tab (I made a Loom video to illustrate [here](https://www.loom.com/share/5b3871361b91482a864b648fb4993622))
