### ISSUE TITLE
[DOCS-515] Added context to values not being returned in API responses

### ISSUE THREAD

**Issue by madalenamelo** [codacy/docs#1607]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [x] Enhancement
-   [ ] Other

**Feedback**

It would be great to have more context to indicate what reasons could cause values not to be returned, specifically, that the API response for the **getRepositoryWithAnalysis** endpoint only returns the `coveragePercentageWithDecimals` and `coveragePercentage` if coverage is uploaded for the last commit on the default branch.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://api.codacy.com/api/api-docs#getrepositorywithanalysis

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment]
This issue was solved in [DOCS-515](https://codacy.atlassian.net/browse/DOCS-515). :heavy_check_mark:
