### ISSUE TITLE
[DOCS-548] Ignoring files page - misleading information about file exclusion from Coverage calculations 

### ISSUE THREAD

**Issue by madalenamelo** [codacy/docs#1684]
**Type of feedback**

-   [x] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

The **Ignoring Files** page mentions that it is possible to exclude files from specific analysis categories, namely Coverage, using a Codacy configuration file. However, it is not possible to use a Codacy configuration file to exclude files from Coverage analysis only - in the Codacy configuration file, the files would have to be excluded from the overall analysis in order to be excluded from the Coverage analysis as well.
![image](https://user-images.githubusercontent.com/72252309/232779680-e0a892d6-25fc-4327-ab5d-cc2099405e87.png)

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/ignoring-files/#ignoring-files

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

There have been some questions around this topic, which leads me to believe that it is not clear, based on our documentation, how files can be excluded from the coverage analysis only. Perhaps it could make sense to add a note or reference to the fact that the only way to achieve this presently is by excluding information for those files from the coverage reports uploaded.

**Comment by prcr** [comment]
For more context see [this](https://codacy.slack.com/archives/C8X9SS1H7/p1681809603610739) and [this](https://codacy.slack.com/archives/C011BCR2RN3/p1681741447370729) internal Slack threads.

**Comment by prcr** [comment]
The pull request https://github.com/codacy/docs/pull/1683 already fixed the incorrect information.
