### ISSUE TITLE
[DOCS-582] The change of `Total lines of code` on Quality dashboard calculated wrongly

### ISSUE THREAD

**Issue by dragon-archer** [codacy/docs#1803]
**Type of feedback**

-   [x] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

Note: Actually I think this isn't a document error but a code error, however I can't find the proper code repo to raise this issue.
It seems that the change(includeing increase or decrease) of `Total lines of code` on Quality dashboard is wrongly divided by 100, you can either remove the '%' or multiply the value before '%' by 100

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories/repository-dashboard/
Note: I think this isn't the real cause of the problem, but perhaps you can add some illustrations here

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

see https://app.codacy.com/gh/dragon-archer/dascript/dashboard?branch=master as an example
The increase of `Total lines of code` between July 20th and July 21st should be either 16.2% or 0.162 instead of 0.162%

**Comment by nicklem** [comment]
Thank you for flagging this issue, @dragon-archer! We forwarded this to the relevant team and will take a look soon.
