### ISSUE TITLE
[DOCS-628] Just a small spelling mistake in the homepage

### ISSUE THREAD

**Issue by yadavan88** [codacy/docs#1982]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [x] Other

**Feedback**

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://www.codacy.com/signup-codacy

It is not a major issue, but a small spelling mistake. In the sign up page, it is given as "Or sing up with Google" instead of "Sign Up". Didnt know where else to report.

![image](https://github.com/codacy/docs/assets/9131956/2bc16505-0d6b-4aaa-8b65-6f1af29c0147)

**Comment by nicklem** [comment]
Thanks for flagging this, @yadavan88! We've notified the relevant team.
