### ISSUE TITLE
[DOCS-171] Missing information on Docs regarding a limit on the number of comments on each PR

### ISSUE THREAD

**Issue by IGFCoimbra** [codacy/docs#265]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

If a PR flags more than 25 issues we will only send 25 comments to the provider. Also, we should have info on the issues that are sent (is it random? Order by the issue's name? By the file's name? )

**Priority**
-   [ ] High
-   [ ] Medium
-   [X] Low

**Comment by pauloribeiro-codacy** [comment]
This is somewhat related to https://codacy.atlassian.net/browse/CY-3229 and perhaps both issues could be fixed at the same time.

**Comment by pauloribeiro-codacy** [comment]
The issue [CY-46](https://codacy.atlassian.net/browse/CY-46) seems to hint that the number of comments on GitHub pull requests was limited by the API that Codacy was using, and that limit no longer exists with GitHub Apps.

Check if the limit of comments per pull requests is still valid and for all Git providers.
