### ISSUE TITLE
Not clear how to add members on synced organization

### ISSUE THREAD

**Issue by paulacodacy** [codacy/docs#40]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**
Support are frequently asked by an administrator about how to add members in a synced organization. It's not very explicit in the description of the link below, because it gives the idea "everything is automatic", so maybe it would be worthy to give more steps in the process of having someone joining the org as a Member. Something along the lines: To become a Codacy Member, the user needs to login in Codacy and select the organization he belongs to (which is shown automatically) and then according to the configuration set up in Organization's Settings > Plan and Billing > "Accepting new people to Codacy", this join can be immediate or pending on owner's approval;

**Affected pages**
This feedback applies to the following documentation pages / URLs:
https://support.codacy.com/hc/en-us/articles/360010263720-What-are-synced-organizations

**Priority**
-   [ ] High
-   [x] Medium
-   [ ] Low

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by pauloribeiro-codacy** [comment]
I'm closing this issue since it will be fixed by [DOCS-113](https://codacy.atlassian.net/browse/DOCS-113).
