### ISSUE TITLE
[DOCS-190] Feedback on "Adding coverage to your repository"

### ISSUE THREAD

**Issue by aarongoldenthal** [codacy/docs#404]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

The `CODACY_API_BASE_URL` must not end in "/" (e.g. https://codacy.somwhere.com vs https://codacy.somwhere.com/) or the upload fails with the error:

```sh
Error [CodacyCoverageReporter] Failed to upload coverage report /builds/my-project/opencover.xml: Request URL not found. Check if the project API Token you are using and the API base URL are valid.  - (CodacyCoverageReporter.scala:25)
```

This should at least be clarified in the documentation, although one could argue this is a big that the code should handle gracefully.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/coverage-reporter/adding-coverage-to-your-repository/

**Comment by pauloribeiro-codacy** [comment]
Thank you @aarongoldenthal for providing this feedback.

We're working on letting the Codacy Coverage Reporter accept URLs with the trailing slash, so we don't have to ask users to leave it out. In the meanwhile, I'll leave this issue open until we release the fix. :+1:

**Comment by pauloribeiro-codacy** [comment]
The Codacy Coverage Reporter now accepts the `CODACY_API_BASE_URL` even if it includes a trailing slash (`/`) since [version 11.7.3](https://github.com/codacy/codacy-coverage-reporter/releases/tag/11.7.3).
