### ISSUE TITLE
[DOCS-167] Update troubleshooting on "Not a member of the organization"

### ISSUE THREAD

**Issue by paulacodacy** [codacy/docs#41]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [ ] Missing information
-   [ ] Outdated information
-   [x] Enhancement
-   [ ] Other

**Feedback**
Now with the synced organization, the "1." of the documentation should be adapted, by mentioning how Members and Authors are added to the synced organization ( we can redirect to the pages about synced organization for when they're updated )

About the "2." part, we frequently get this situation, I'm not sure if most of users check this particular documentation for guidance on the resolution, although when they do, it might not be very intuitive. Here's my simplified version (feel free to change and improve):

> 2. The email used to commit belongs to an already added collaborator, but it's not associated with the collaborator's Codacy account. Email addresses on a Codacy account are based on the associated code provider account, so in order to solve this, the collaborator needs to make sure the missing email is in the code provider account and then re-login in Codacy to update the account's emails. 

**Affected pages**
This feedback applies to the following documentation pages / URLs:
https://support.codacy.com/hc/en-us/articles/115001959985-Why-do-I-get-a-Not-a-member-of-the-organization-message-

**Priority**
-   [ ] High
-   [x] Medium
-   [ ] Low

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by pauloribeiro-codacy** [comment]
Reviewed and updated the page:

https://docs.codacy.com/faq/troubleshooting/not-a-member-of-the-organization/
