### ISSUE TITLE
[DOCS-194] Feedback on "Codacy configuration file"

### ISSUE THREAD

**Issue by kvudata** [codacy/docs#429]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

How do I disable complexity analysis on a file?

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/codacy-configuration-file/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

none

**Comment by pauloribeiro-codacy** [comment]
Thank you for the feedback @kvudata,

The complexity analysis can be toggled using the **Metrics** category:

> The category metrics refers to the information you find under File details such as Size, Structure and Complexity.

However, if you were using the Codacy configuration file example on the documentation page to get you started, the YAML section for the Metrics category had a typo. We're currently fixing it on the pull request https://github.com/codacy/docs/pull/436.

Please let us know if this helps.

**Comment by kvudata** [comment]
Ah I see, it wasn't obvious to me that metrics controls complexity along
with other things - I was expecting an option/engine specific to each of
the metrics. This should work for my needs.

**Comment by pauloribeiro-codacy** [comment]
Hello @kvudata, did you have any success implementing the solution that I gave you?

There was another Codacy user that wasn't able to make it work, and so our development teams will be investigating what could be the issue. But in the meantime, I'm removing the information that we're not sure about from the documentation page (https://github.com/codacy/docs/pull/446).

**Comment by kvudata** [comment]
I ended up working around the code complexity another way so ended up not
testing this
