### ISSUE TITLE
[DOCS-196] Clarify complete syntax of Codacy configuration file

### ISSUE THREAD

**Issue by prcr** [codacy/docs#437]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

We should provide a full description of the syntax for the Codacy configuration file, with all available configurations. Perhaps this can be done by providing a more complete example that covers all possible configurations.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/codacy-configuration-file/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

This issue was created from #429.

**Comment by pauloribeiro-codacy** [comment]
Wait for the result of [CY-3679](https://codacy.atlassian.net/browse/CY-3679) before advancing with this issue.

**Comment by mrfyda** [comment]
@prcr looks like there is a way to specify the schema of configuration files and make it available for (some) IDEs: https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier/

![Screenshot 2021-04-16 at 14 51 31](https://user-images.githubusercontent.com/593860/115034310-43e7ad00-9ec3-11eb-807e-e50be882d35d.png)

do you think it would be interesting to pursue this?
https://github.com/mrfyda/schemastore/commit/69ca64a1a4c77a3664ba75606773bbf79080c10a

we look at documenting the schema on the docs, but this looks more usable 😁

**Comment by prcr** [comment]
@mrfyda The main issue right now is that we found out that the Codacy configuration file actually supports fewer options than expected (see [CY-3679](https://codacy.atlassian.net/browse/CY-3679) and the resulting Epic [CY-3985](https://codacy.atlassian.net/browse/CY-3985)).

Even so, if we could provide a schema that reflected the current options that we support, it would be helpful for customers. Besides that, it's also a formal way of describing the allowed syntax, which can help maintain the examples in the documentation in sync. :nerd_face: :+1: 

I'll have a closer look at your changes in the next few days and then perhaps we can open a pull request on the original repository? :muscle:

**Comment by mrfyda** [comment]
got it!

nice that the team is looking into this. the current format of the configuration file doesn't make it easy to document with a json schema. a few changes would help!

**Comment by prcr** [comment]
See also #670 and the subsequent revert in #906 for clarification of duplication configuration options.

**Comment by prcr** [comment]
I'm closing this issue since we won't be tackling the documentation updates unless there's some product investment in the Codacy configuration file feature.
