### ISSUE TITLE
[DOCS-202] Add information regarding tools that don't support config files

### ISSUE THREAD

**Issue by IGFCoimbra** [codacy/docs#473]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

Our documentation regarding the tool's configuration files has info regarding all the files supported for each tool but makes no mention to the tool that doesn't support any type of configuration file. While we can just assume that the page is correct and tools that aren't mentioned do not support a config file simply don't appear on this list, it could be more explicit to have a note at the end with the list of tools that don't support a config file. This way we can be sure that no tool was forgotten (as the two lists should have all of the tools we support among them) and it will be more clear to our users who, as is, might just assume that the page is not updated or that we forgot one tool.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/code-patterns/#using-your-own-tool-configuration-files

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

We had one user reaching out to support asking how he could set up a config file for Scala Meta Pro, as no information was provided on the documentation page.  We explained to the user that all tools not in the list don't support a config file

**Comment by pauloribeiro-codacy** [comment]
@IGFCoimbra, I propose the quick improvement in #475 until we have a more definite solution for this.

**Comment by prcr** [comment]
@jamescodacy also gave similar feedback since he was searching for the Checkov configuration files:

https://codacy.slack.com/archives/C8X9SS1H7/p1617194887005500

**Comment by prcr** [comment]
The recently added tool markdownlint is missing from the table.
