### ISSUE TITLE
[DOCS-277] Feedback on "Adding coverage to your repository"

### ISSUE THREAD

**Issue by madalenamelo** [codacy/docs#757]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [x] Enhancement
-   [ ] Other

**Feedback**

In the second point of "2. Uploading coverage data to Codacy", one of the variables that must be specified is the CODACY_USERNAME. However, this field should only contain the username if the org is personal, otherwise the CODACY_USERNAME should be the organization's name, otherwise it will generate an error. This is not very clear in the current documentation.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/v4.0/coverage-reporter/#uploading-coverage

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment]
@madalenamelo, please check the pull request https://github.com/codacy/codacy-coverage-reporter/pull/330 to see if correctly addresses the issue.
