### ISSUE TITLE
Add authentication token to Codacy API v2.0 examples

### ISSUE THREAD

**Issue by pauloribeiro-codacy** [codacy/docs#80]
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**
A customer asked:

> Hi,
>
> Is there an example for the authentication API? The example browser on the right side of the page skips to examples for “commit”, and none of the examples that are present include any authentication components.

This was caused by the examples not being clear that one needs to include an extra header with the authentication token.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

-   https://api.codacy.com/swagger#codacy-api

**Priority**
-   [ ] High
-   [X] Medium
-   [ ] Low

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

See email with subject "Fwd: Example for the Authentication API?" for more context.

**Comment by pauloribeiro-codacy** [comment]
I'm closing this issue since this improvement will be done in the scope of documentation improvements for the Codacy API v3 ([DOCS-42](https://codacy.atlassian.net/browse/DOCS-42)).

**Comment by prcr** [comment]
This issue ended up being solved by [DOCS-224](https://codacy.atlassian.net/browse/DOCS-224).
