### ISSUE TITLE
[DOCS-289] Feedback on "Adding coverage to your repository"

### ISSUE THREAD

**Issue by madalenamelo** [codacy/docs#807]
**Type of feedback**

-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

Missing information on uploading coverage for multiple languages in a repository.

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/coverage-reporter/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

When working with multiple languages on a repository, we recommend that users send separate coverage reports, one for each language  but another possible workaround for this would be uploading the same file twice specifying `-l [language]` on each upload. These options are currently no referred in the documentation.

**Comment by prcr** [comment]
Hello @madalenamelo, please check the pull request https://github.com/codacy/codacy-coverage-reporter/pull/348 for a possible solution to improve this scenario.

**Comment by prcr** [comment]
The information on how to upload information for several languages coming from the same coverage report is now available at https://docs.codacy.com/coverage-reporter/#multiple-languages.
